version: 2.1

commands:
    install_and_test:
        parameters:
            composer_flags:
                type: string
                default: ""
            laravel:
                type: string
                default: ""
            phpunit_flags:
                type: string
                default: ""
        steps:
            - checkout
            - run: echo 'export APP_ENV="test"' >> $BASH_ENV
            - run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
            - run: composer self-update
            - run: composer require "laravel/framework=<< parameters.laravel >>" --prefer-source --no-interaction --no-suggest --no-update
            - run: if [ "<< parameters.laravel >>" == "5.7.*" ]; then composer require "laravel/telescope=~1.0" --prefer-source --no-interaction --no-suggest --no-update --dev; fi
            - run: if [ "<< parameters.laravel >>" == "5.8.*" ]; then composer require "laravel/telescope=~2.0" --prefer-source --no-interaction --no-suggest --no-update --dev; fi
            - run: composer update << parameters.composer_flags >> --no-interaction --prefer-source
            - run: vendor/bin/phpunit << parameters.phpunit_flags >>

workflows:
    version: 2
    build:
        jobs:
            - php71-laravel55
            - php71-laravel55-prefer-lowest
            - php72-laravel55
            - php72-laravel55-prefer-lowest
            - php73-laravel55
            - php73-laravel55-prefer-lowest
            - php71-laravel56
            - php71-laravel56-prefer-lowest
            - php72-laravel56
            - php72-laravel56-prefer-lowest
            - php73-laravel56
            - php73-laravel56-prefer-lowest
            - php71-laravel57
            - php71-laravel57-prefer-lowest
            - php72-laravel57
            - php72-laravel57-prefer-lowest
            - php73-laravel57
            - php73-laravel57-prefer-lowest
            - php71-laravel58
            - php71-laravel58-prefer-lowest
            - php72-laravel58
            - php72-laravel58-prefer-lowest
            - php73-laravel58
            - php73-laravel58-prefer-lowest

jobs:
    php71-laravel55-prefer-lowest:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.5.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php71-laravel55:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.5.*
                  phpunit_flags: --no-coverage
    php72-laravel55-prefer-lowest:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.5.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php72-laravel55:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.5.*
                  phpunit_flags: --no-coverage
    php73-laravel55-prefer-lowest:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.5.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php73-laravel55:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.5.*

    php71-laravel56-prefer-lowest:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php71-laravel56:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  phpunit_flags: --no-coverage
    php72-laravel56-prefer-lowest:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php72-laravel56:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  phpunit_flags: --no-coverage
    php73-laravel56-prefer-lowest:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php73-laravel56:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.6.*
                  phpunit_flags: --no-coverage
    php71-laravel57-prefer-lowest:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php71-laravel57:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  phpunit_flags: --no-coverage
    php72-laravel57-prefer-lowest:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php72-laravel57:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  phpunit_flags: --no-coverage
    php73-laravel57-prefer-lowest:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  composer_flags: --prefer-lowest
                  phpunit_flags: --no-coverage
    php73-laravel57:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  phpunit_flags: --no-coverage
    php71-laravel58-prefer-lowest:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.8.*
                  composer_flags: --prefer-lowest
    php71-laravel58:
        docker:
            - image: circleci/php:7.1
        steps:
            - install_and_test:
                  laravel: 5.8.*
    php72-laravel58-prefer-lowest:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.8.*
                  composer_flags: --prefer-lowest
    php72-laravel58:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.8.*
    php73-laravel58-prefer-lowest:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.8.*
                  composer_flags: --prefer-lowest
    php73-laravel58:
        docker:
            - image: circleci/php:7.3
        steps:
            - install_and_test:
                  laravel: 5.8.*
