name: run-js-tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Install dependencies
              run: yarn install --non-interactive

            - name: Execute tests
              run: yarn run jest
